### ISSUE TITLE
Magazine Wells support

### ISSUE THREAD

**Issue by dedmen** [the0utsider/mag-drop#1]
Here you check out of ammo for magazine compatible to the current weapon

https://github.com/the0utsider/mag-drop/blob/master/goko_drop_magz/Functions/fn_FiredEH_mainHook.sqf#L17

But you only check the magazines array in the weapon class and you completely ignore magazineWells. A weapon might have dozens of compatible magazines, but a empty magazines array thus the `_bOutofAmmo` will be true too soon.
Also arrayIntersect is unsafe as the names in the magazines array are not necessarily the correct case as the ones returned by `magazines` command.

Just use the CBA command
https://github.com/CBATeam/CBA_A3/blob/master/addons/common/fnc_compatibleMagazines.sqf
It also caches values making your FiredEH more efficient, and it also takes care of case-sensitive correct names so you can more easily compare with the result of the `magazines` command.

**Comment by ygokmen** [comment]
Thanks for feedback & solution!
implementing your solution will make this hacky-reload EH more efficient for sure. Until next A3 update.

I was trying to pinpoint this issue until few weeks ago, but BI have fixed their muzzle reload EH @DEV branch. A true reload EH makes this hacky-reload detection and it's 'available magazines check' obsolete, here: https://github.com/the0utsider/mag-drop/blob/1.91xDEV/addons/goko_drop_magz/Functions/fn_Muzzle_ReloadEH.sqf

**Comment by dedmen** [comment]
>A true reload EH makes this hacky-reload detection and it's 'available magazines check' obsolete

As far as I heard new EH's were config only though.
Oh I see you are adding it to the config.
That won't work for any weapons that add their own reload EH, because they will overwrite yours.
