### ISSUE TITLE
Formula to rotate object and set its position so models in nameSpecial string can be used.

### ISSUE THREAD

**Issue by ygokmen** [the0utsider/mag-drop#4]
https://community.bistudio.com/wiki/BIS_fnc_createSimpleObject
_used in_ https://github.com/the0utsider/mag-drop/blob/master/goko_drop_magz/Functions/TransformIntoSimpleObject.sqf

Terrain inclination boolean in this function helps greatly, it aligns the spawned magazines beautifully without dealing with setVectorDirAndUp. Downside, when you try to use magazines at nameSpecial string of magazine's Cfg, because of their rotation, they stand up on ground with one half of them buried to the ground...you have to set Dir and Up vectors manually.

Probably because of their usage (these are what we see attached to weapon's magazine slot), these models are aligned upright, 90 degrees tilt on X axis (or Y).

So far I couldn't manage to write a formula to set their dir and up vectors manually and having them standing sideways, just like magazines spawned by mod right now. 

**PROBLEM:** on terrain, spawning a nameSpecial model requires 2 operations: 
Rotation on X (or Y), and with that a surface normal calculation according to surface player is on... player model is the only thing we can take as reference.  @dedmen  @commy2

_NOTE:_ you can still use terrain inclination bool true, then use setVectorDirAndUp to do the rotation/corrections. Which I couldn't manage as well.

**This will get rid of placeholder "generic rifle magazine" model for many weapons, probably ALL BI vanilla magazines have their own models under nameSpecial. More came with latest DEV build as well.**

**Comment by ygokmen** [comment]
this kinda works..needs through testing
`
_unit = player; 
_pos = AGLToASL getPosAtL _unit; 
_model = "a3\Weapons_F\MagazineProxies\mag_65x39c_mx_30rnd.p3d"; 
 
_stringoro = 
[  
	[  
	"",       
	_model,    
	0,        
	0,       
	[],        
	[]         
	],   
	_pos,       
	round(random 359),      
	true,         
	true        
] call BIS_fnc_createSimpleObject; 

_stringoro setvectordirandup  
[ 
	[0,0,0] vectordiff surfacenormal getpos _unit ,

	[-1 +random 2,-1 +random 2,-1] vectorCrossProduct surfacenormal getpos _unit 
];
`

**Comment by the0utsider** [comment]
`_unit = player; 
_pos = AGLToASL getPosAtL _unit; 
_model = "a3\Weapons_F\MagazineProxies\mag_65x39c_mx_30rnd.p3d"; 
 
_stringoro = 
[  
	[  
	"",       
	_model,    
	0,        
	0,       
	[],        
	[]         
	],   
	_pos,       
	round(random 359),      
	true,         
	true        
] call BIS_fnc_createSimpleObject; 

_stringoro setvectordirandup  
[ 
	[0,0,0] vectordiff surfacenormal getpos _unit ,

	[-1 +random 2,-1 +random 2,-1] vectorCrossProduct surfacenormal getpos _unit 
];`
